#!/usr/bin/env bash
set -u

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || exit 1

parent_root="$(cd "$repo_root/.." && pwd)"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$parent_root/.cargo-target}"

work_dir="$(mktemp -d "${TMPDIR:-/tmp}/astra-p57.XXXXXX")"
trap 'rm -rf "$work_dir"' EXIT

mkdir -p docs/validation artifacts/p57

timestamp_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
git_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || printf unknown)"
git_commit="$(git rev-parse HEAD 2>/dev/null || printf unknown)"
cargo_path="$(command -v cargo || true)"
rustc_path="$(command -v rustc || true)"
cargo_version="$("$cargo_path" --version 2>/dev/null || printf unavailable)"
rustc_version="$("$rustc_path" --version 2>/dev/null || printf unavailable)"
github_actions_status="${P57_GITHUB_ACTIONS_STATUS:-}"
github_actions_url="${P57_GITHUB_ACTIONS_URL:-}"
github_actions_run_id="${P57_GITHUB_ACTIONS_RUN_ID:-}"

cargo_fmt_check=NOT_RUN
cargo_build_workspace=NOT_RUN
cargo_test_workspace=NOT_RUN
check_p53_strict=NOT_RUN
export_p53_strict_json=NOT_RUN
bench_smoke=NOT_RUN
runtime_smoke=NOT_RUN
metrics_json=NOT_RUN
p57_report_json=NOT_RUN
invalid_examples_rejected=NOT_RUN
invalid_checked=0
invalid_rejected=0
failures=0
invalid_rows=""

run_gate() {
  local var_name="$1"
  local label="$2"
  shift 2
  local log_file="$work_dir/$var_name.out"

  if "$@" >"$log_file" 2>&1; then
    printf -v "$var_name" PASS
  else
    printf -v "$var_name" FAIL
    failures=$((failures + 1))
    printf 'FAIL: %s\n' "$label" >&2
    tail -n 40 "$log_file" >&2
  fi
}

run_shell_gate() {
  local var_name="$1"
  local label="$2"
  local command="$3"
  local log_file="$work_dir/$var_name.out"

  if bash -c "$command" >"$log_file" 2>&1; then
    printf -v "$var_name" PASS
  else
    printf -v "$var_name" FAIL
    failures=$((failures + 1))
    printf 'FAIL: %s\n' "$label" >&2
    tail -n 40 "$log_file" >&2
  fi
}

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

json_string_or_null() {
  if [ -z "$1" ]; then
    printf 'null'
  else
    printf '"%s"' "$(json_escape "$1")"
  fi
}

run_gate cargo_fmt_check "cargo fmt --all -- --check" \
  cargo fmt --all -- --check
run_gate cargo_build_workspace "cargo build --workspace" \
  cargo build --workspace
run_gate cargo_test_workspace "cargo test --workspace" \
  cargo test --workspace
run_gate check_p53_strict "check examples/p53_strict.atlas" \
  cargo run -p atlas-cli -- check examples/p53_strict.atlas
run_shell_gate export_p53_strict_json "export examples/p53_strict.atlas --format json" \
  "cargo run -p atlas-cli -- export examples/p53_strict.atlas --format json > '$work_dir/p53_strict.json' && diff -u tests/golden/p53_strict.json '$work_dir/p53_strict.json'"
run_gate bench_smoke "bench --mode smoke" \
  cargo run -p atlas-cli -- bench --mode smoke
run_gate runtime_smoke "run examples/p53_strict.atlas --mode smoke" \
  cargo run -p atlas-cli -- run examples/p53_strict.atlas --mode smoke
run_shell_gate metrics_json "metrics examples/p53_strict.atlas --format json" \
  "cargo run -p atlas-cli -- metrics examples/p53_strict.atlas --format json > '$work_dir/p56_metrics.json'"
run_shell_gate p57_report_json "report examples/p53_strict.atlas --format json" \
  "cargo run -p atlas-cli -- report examples/p53_strict.atlas --format json > '$work_dir/p57_report.json' && diff -u tests/golden/p57_report.json '$work_dir/p57_report.json'"

for invalid_file in examples/invalid/*.atlas; do
  invalid_checked=$((invalid_checked + 1))
  log_file="$work_dir/invalid-$(basename "$invalid_file").out"
  if cargo run -p atlas-cli -- check "$invalid_file" >"$log_file" 2>&1; then
    invalid_rows="${invalid_rows}| \`$invalid_file\` | FAIL | accepted unexpectedly |\n"
  else
    invalid_rejected=$((invalid_rejected + 1))
    observed="$(grep -Eo 'E_[A-Z0-9_]+' "$log_file" | head -n 1 || true)"
    invalid_rows="${invalid_rows}| \`$invalid_file\` | PASS | ${observed:-rejected} |\n"
  fi
done

if [ "$invalid_checked" -eq "$invalid_rejected" ] && [ "$invalid_checked" -gt 0 ]; then
  invalid_examples_rejected=PASS
else
  invalid_examples_rejected=FAIL
  failures=$((failures + 1))
fi

if [ -n "$github_actions_status" ]; then
  trace_status=LOCAL_PASS_CI_PASS
else
  trace_status=LOCAL_PASS_CI_REQUIRED
fi

if [ "$failures" -gt 0 ]; then
  trace_status=LOCAL_FAIL
fi

p57_report_block="{}"
if [ -f "$work_dir/p57_report.json" ]; then
  p57_report_block="$(cat "$work_dir/p57_report.json")"
fi

cat >docs/validation/astra-p57-validation-summary.md <<EOF
# ASTRA-P57 validation summary

Generated by \`scripts/validate_p57_local.sh\`.

## Git context

- Branch: \`$git_branch\`
- Commit: \`$git_commit\`
- Date UTC: \`$timestamp_utc\`

## Environment

- Cargo: \`${cargo_path:-unavailable}\`
- Rustc: \`${rustc_path:-unavailable}\`
- Cargo version: \`$cargo_version\`
- Rustc version: \`$rustc_version\`
- Cargo target dir: \`$CARGO_TARGET_DIR\`

## Required gates

| Gate | Status |
|---|---|
| cargo fmt --all -- --check | $cargo_fmt_check |
| cargo build --workspace | $cargo_build_workspace |
| cargo test --workspace | $cargo_test_workspace |
| check examples/p53_strict.atlas | $check_p53_strict |
| export examples/p53_strict.atlas --format json | $export_p53_strict_json |
| bench --mode smoke | $bench_smoke |
| run examples/p53_strict.atlas --mode smoke | $runtime_smoke |
| metrics examples/p53_strict.atlas --format json | $metrics_json |
| report examples/p53_strict.atlas --format json | $p57_report_json |
| invalid examples rejected | $invalid_examples_rejected, $invalid_rejected rejected / $invalid_checked checked |
| GitHub Actions CI | ${github_actions_status:-not recorded by local script} |

## P57 report summary

\`\`\`json
$p57_report_block
\`\`\`

## Invalid examples

| Example | Status | Observed |
|---|---|---|
$(printf '%b' "$invalid_rows")

## Final validation trace status

\`$trace_status\`

## GitHub Actions status

- Status: \`${github_actions_status:-null}\`
- URL: $(json_string_or_null "$github_actions_url")
- Run ID: $(json_string_or_null "$github_actions_run_id")

## Notes

- CLI report decision remains conservative as \`RECALIBRATE_P57\` unless CI
  evidence is provided through an explicit future mechanism.
- This summary is compact and omits raw logs by design.
EOF

cat >artifacts/p57/astra-p57-validation-summary.json <<EOF
{
  "astra_iteration": "ASTRA-P57",
  "timestamp_utc": "$(json_escape "$timestamp_utc")",
  "git_branch": "$(json_escape "$git_branch")",
  "git_commit": "$(json_escape "$git_commit")",
  "environment": {
    "cargo": "$(json_escape "${cargo_path:-unavailable}")",
    "rustc": "$(json_escape "${rustc_path:-unavailable}")",
    "cargo_version": "$(json_escape "$cargo_version")",
    "rustc_version": "$(json_escape "$rustc_version")",
    "cargo_target_dir": "$(json_escape "$CARGO_TARGET_DIR")"
  },
  "required_gates": {
    "cargo_fmt_check": "$cargo_fmt_check",
    "cargo_build_workspace": "$cargo_build_workspace",
    "cargo_test_workspace": "$cargo_test_workspace",
    "check_p53_strict": "$check_p53_strict",
    "export_p53_strict_json": "$export_p53_strict_json",
    "bench_smoke": "$bench_smoke",
    "runtime_smoke": "$runtime_smoke",
    "metrics_json": "$metrics_json",
    "p57_report_json": "$p57_report_json",
    "invalid_examples_rejected": {
      "status": "$invalid_examples_rejected",
      "checked": $invalid_checked,
      "rejected": $invalid_rejected
    }
  },
  "p57_report": $p57_report_block,
  "validation_trace_status": "$trace_status",
  "github_actions_status": $(json_string_or_null "$github_actions_status"),
  "github_actions_url": $(json_string_or_null "$github_actions_url"),
  "github_actions_run_id": $(json_string_or_null "$github_actions_run_id"),
  "blockers": []
}
EOF

if [ "$failures" -gt 0 ]; then
  printf 'ASTRA-P57 local validation failed: %s gate(s) failed.\n' "$failures" >&2
  exit 1
fi

printf 'ASTRA-P57 local validation summary written.\n'
